# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date_visited',
            field=models.CharField(default='not visited', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='review',
            field=models.CharField(default='not visited', max_length=300),
        ),
    ]
